[package]
name = "miniscript-tabconf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "miniscript_tabconf"
crate-type = ["cdylib"]

[dependencies]
bitcoin = "0.30.1"
miniscript = "10.0.0"
pyo3 = "0.19.0"
